### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by amirmrad** [mlabs-haskell/radix-snapshot-poll-concept#3]
- [x] Cleanup back-end express code. Restructure API controllers and extract environment variables.
- [x] Cleanup all scripts rust and TS. Create more modular helpers. Delete unused/not working scripts from repo.
- [x] Remove scrypto code left-over from original contract code. Remove related tests and scripts.

**Comment by mikekeke** [comment]
Done in several distinct PRs.
